### ISSUE TITLE
Profiles branch bug

### ISSUE THREAD

**Issue by melanybelzile** [DFOglider/pilotingApp#6]
Doesn't work for SEA019 M36.

**Comment by richardsc** [comment]
Just to confirm, is this the error you get?
```
Warning: Error in [: only 0's may be mixed with negative subscripts
Stack trace (innermost first):
    70: NextMethod
    69: [.POSIXct
    68: [
    67: findProfilesSOCIB
    66: readSeaExplorerRealTime
    65: observeEventHandler [/Users/richardsc/git/pilotingApp/app.R#204]
     1: runApp
```

**Comment by richardsc** [comment]
I think the problem here has to do with an inital profile that is totally wonky because of the buoy, so the profile detection that @clayton33 coded is simply failing. 

Commit adf4f67be90c5173548d33996cad0903be7f5d4d "fixes" the problem by simply specifying that we will never want to see the first profile (since it's always the buoy dive). It's a bit of a kludge but I can't think of why we'd need to see that profile.

@melanybelzile Can you pull the `profilePlots` branch and test? If it seems to work, you can go ahead and close the issue.

**Comment by melanybelzile** [comment]
Yes that was the error I got. I won't close this until we figure out the 2 issues together ;)

**Comment by richardsc** [comment]
I'm going to close this, because the title is vague and the issue that it addressed has been "solved". 

However, I'm about to open another (more specific) issue, that I think by proxy will take care of this case too.
